abstract class PersonalSettingsEditStates{}

class PersonalSettingsEditInitialState extends PersonalSettingsEditStates{}

class PersonalSettingsEditSuccessGetUserDataState extends PersonalSettingsEditStates{}

class PersonalSettingsEditLoadingUpdateUserDataState extends PersonalSettingsEditStates{}

class PersonalSettingsEditSuccessUpdateUserDataState extends PersonalSettingsEditStates{}

class PersonalSettingsEditSuccessEndState extends PersonalSettingsEditStates{}

class PersonalSettingsEditErrorUpdateUserDataState extends PersonalSettingsEditStates{

  final String error;

  PersonalSettingsEditErrorUpdateUserDataState(this.error);

}
